import type { LucideProps } from "lucide-react";
import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  Archive,
  Bell,
  Blocks,
  BookOpen,
  Box,
  Boxes,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  Clock3,
  Cloud,
  Code2,
  Command,
  Copy,
  Cpu,
  CreditCard,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Folder,
  Gamepad2,
  Gauge,
  GitBranch,
  Globe2,
  HardDrive,
  KeyRound,
  Layers3,
  LayoutDashboard,
  LifeBuoy,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  MemoryStick,
  Menu,
  MessageSquare,
  MonitorCog,
  MoreHorizontal,
  Network,
  Play,
  PlugZap,
  Power,
  Plus,
  Radio,
  Rocket,
  RotateCcw,
  Search,
  Send,
  Server,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Terminal,
  UserRound,
  WalletCards,
  Waypoints,
  Wifi,
  Workflow,
  X,
  Zap
} from "lucide-react";

const icons = {
  activity: Activity,
  arrow: ArrowRight,
  "arrow-up-right": ArrowUpRight,
  archive: Archive,
  bell: Bell,
  blocks: Blocks,
  book: BookOpen,
  box: Box,
  boxes: Boxes,
  check: Check,
  "check-circle": CheckCircle2,
  chevron: ChevronRight,
  "chevron-down": ChevronDown,
  code: Code2,
  command: Command,
  copy: Copy,
  cpu: Cpu,
  credit: CreditCard,
  database: Database,
  disk: HardDrive,
  external: ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: FileText,
  folder: Folder,
  gamepad: Gamepad2,
  gauge: Gauge,
  git: GitBranch,
  globe: Globe2,
  key: KeyRound,
  layers: Layers3,
  layout: LayoutDashboard,
  life: LifeBuoy,
  lock: LockKeyhole,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  memory: MemoryStick,
  menu: Menu,
  message: MessageSquare,
  monitor: MonitorCog,
  more: MoreHorizontal,
  network: Network,
  play: Play,
  plug: PlugZap,
  power: Power,
  plus: Plus,
  radio: Radio,
  rocket: Rocket,
  restart: RotateCcw,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings2,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  spark: Sparkles,
  terminal: Terminal,
  user: UserRound,
  wallet: WalletCards,
  waypoints: Waypoints,
  wifi: Wifi,
  workflow: Workflow,
  x: X,
  bolt: Zap,
  cloud: Cloud,
  money: CircleDollarSign
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={1.8} {...props} />;
}
